#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_fsm_clktick.sv --exe f1_fsm_clktick_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_fsm_clktick.mk Vf1_fsm_clktick

# run executable simulation file
obj_dir/Vf1_fsm_clktick