#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_starting_light.sv --exe f1_starting_light.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_starting_light.mk Vf1_starting_light

# run executable simulation file
obj_dir/Vf1_starting_light